[http]
# HTTP server settings
port = 3000
host = "0.0.0.0"

# Worker determination strategy
# Could be either:
# - path: Best for local testing. Like `localhost:3000/worker/worker-name`
# - subdomain-name: Best for production. Like `worker-name.example.com`
determination-strategy = "path"

[runtime]
# Worker architectural settings
pods = 100  # the amount of pods (threads)
workers-per-pod = 2  # the amount of workers per pod (thread)


# ===== Worker feature settings =====

# These are the *allowed* bindings for every worker
# The bindings specified here can connect to the bindings
# server if they identify themselves correctly.
#
# See: https://svld.aweird.me/docs/bindings/protocol
bindings = [
    # "my-binding-1",
    # "my-binding-2",
]
